install.packages("readxl")
install.packages("tidyverse")
install.packages('ggmap')
install.packages('purrr')
library(readxl)
library(tidyverse)
library(ggmap)
library(purrr)
library(knitr)
library(ggplot2)

tables <- list(anthem, bright, cigna)
all_carriers <- reduce(tables, bind_rows, AnthemBCBS = anthem, Bright = bright, Cigna = cigna)