install.packages("readxl")
install.packages("tidyverse")
install.packages('ggmap')
install.packages('purrr')
install.packages("stringr")
install.packages("magick")
install.packages("here")
library(readxl)
library(tidyverse)
library(ggmap)
library(purrr)
library(knitr)
library(ggplot2)
library(stringr)
library(magick)
library(here) # For making the script run without a wd
library(magrittr) # For piping the logo